### ISSUE TITLE
Didn't find class "io.grpc.okhttp.OkHttpChannelBuilder"

### ISSUE THREAD

**Issue by Jawadwithw** [heroiclabs/nakama-java#22]
After adding the  nakama-java-2.0.0.jar file to my android project and add that as library to dependency , i get this error:
java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/okhttp/OkHttpChannelBuilder;
        at com.heroiclabs.nakama.DefaultClient.<init>(DefaultClient.java:104)
        at com.heroiclabs.nakama.DefaultClient.<init>(DefaultClient.java:72)
        at develop.withw.hura25.G.initNakama(G.java:49)
        at develop.withw.hura25.G.onCreate(G.java:23)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.grpc.okhttp.OkHttpChannelBuilder" on path: DexPathList[[zip file "/data/app/develop.withw.hura25-2/base.apk"],nativeLibraryDirectories=[/data/app/develop.withw.hura25-2/lib/arm, /system/lib, /vendor/lib, /system/vendor/lib]]
    
ps : I have already added multiDexEnabled true ind default config

can anybody help me please?!

**Comment by samuelowino** [comment]
OSS

**Comment by mofirouz** [comment]
@samuelowino Not sure what you mean by `OSS`?

**Comment by samuelowino** [comment]
Fighting with this same problem right now, came here for help but doesn't look like that's the kind of thing offered on this project.

**Comment by mofirouz** [comment]
@samuelowino This is all basic Java dependency management. You’ve chosen to pull in the JAR which is not the uber JAR so it doesn’t contain the dependencies nested inside the JAR. The usual workflow is to look at the dependencies for this code and add the relevant ones to your Maven or Gradle dependencies.

Your response is not welcome to this project or the Heroic community. It is neither constructive or contributive to the codebase. Please contribute to OSS rather than use passive aggressive comments to extract time from the community. What do you think could be done to make this project easier to integrate?

**Comment by samuelowino** [comment]
If you added the first paragraph of your reply to this issue when @Jawadwithw opened it, you would have helped everyone who is experiencing this problem and maybe gotten some useful feedback instead you just closed the issue.

For instance adding the said missing dependence doesn't solve the problem instead it cause other errors related to other dependencies.

sl4j
Stackworth being once I have seen while trying to add 2.0.4

**Comment by mofirouz** [comment]
@samuelowino “doesn’t solve the problem” has already been solved and explained that you should look at the dependency tree to ensure you pull in the related deps that the Nakama client depends on. Take a look at this file for the very small set of dependencies this project relies on:

https://github.com/heroiclabs/nakama-java/blob/master/build.gradle#L53

I’ll lock this issue because it has become unfriendly all round.
