### ISSUE TITLE
Unable to connect with Nakama server

### ISSUE THREAD

**Issue by mthakuri** [heroiclabs/nakama-java#34]
**Tech Stack info**
Gradle plugin: 4.0.0
Gradle: 6.1.1
Compile SDK: 29
build tool: 30.0.1
libs: **nakama-java-2.0.4-all.jar**
NakaServer  v2.11.1 with cocroachdb v19.2

**Step to reproduce**
1. Create a new Android project 
2. Add the nakama-java-2.0.4-all.jar into the libs folder
3. Write the below code in activity

> public void connectToNakama() {
        try {
            Client client = new DefaultClient("defaultkey", "13.233.18.135", 7350, false);
            String id = UUID.randomUUID().toString();
            Session session = client.authenticateCustom(id).get();
            SocketClient socket = client.createSocket();
            SocketListener listener = new AbstractSocketListener() {
                @Override
                public void onDisconnect(final Throwable t) {
                    System.out.println("Socket disconnected.");
                }
            };
            socket.connect(session, listener).get();
            System.out.println("Socket connected.");
        } catch (ExecutionException | InterruptedException e) {
            e.printStackTrace();
        }
    }

I'm calling this code from a thread

**Issue**
I'm getting following error:

> 2020-07-13 18:25:48.057 15856-15889/com.parshu.nakamademo W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2020-07-13 18:25:48.058 15856-15889/com.parshu.nakamademo W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
2020-07-13 18:25:48.058 15856-15889/com.parshu.nakamademo W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-07-13 18:25:48.091 15856-15890/com.parshu.nakamademo D/OpenGLRenderer: HWUI GL Pipeline
2020-07-13 18:25:48.245 15856-15889/com.parshu.nakamademo W/System.err: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: error in frame handler
2020-07-13 18:25:48.245 15856-15889/com.parshu.nakamademo W/System.err:     at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531)
2020-07-13 18:25:48.245 15856-15889/com.parshu.nakamademo W/System.err:     at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:512)
2020-07-13 18:25:48.246 15856-15889/com.parshu.nakamademo W/System.err:     at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
2020-07-13 18:25:48.246 15856-15889/com.parshu.nakamademo W/System.err:     at com.parshu.nakamademo.MainActivity.connectToNakama(MainActivity.java:35)
2020-07-13 18:25:48.246 15856-15889/com.parshu.nakamademo W/System.err:     at com.parshu.nakamademo.MainActivity$1.run(MainActivity.java:26)
2020-07-13 18:25:48.246 15856-15889/com.parshu.nakamademo W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-07-13 18:25:48.247 15856-15889/com.parshu.nakamademo W/System.err: Caused by: io.grpc.StatusRuntimeException: INTERNAL: error in frame handler
2020-07-13 18:25:48.247 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.Status.asRuntimeException(Status.java:533)
2020-07-13 18:25:48.247 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
2020-07-13 18:25:48.247 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
2020-07-13 18:25:48.247 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
2020-07-13 18:25:48.248 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
2020-07-13 18:25:48.248 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
2020-07-13 18:25:48.249 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
2020-07-13 18:25:48.249 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
2020-07-13 18:25:48.249 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
2020-07-13 18:25:48.250 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
2020-07-13 18:25:48.250 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
2020-07-13 18:25:48.250 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
2020-07-13 18:25:48.250 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
2020-07-13 18:25:48.251 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
2020-07-13 18:25:48.251 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:632)
2020-07-13 18:25:48.251 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2020-07-13 18:25:48.251 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2020-07-13 18:25:48.251 15856-15889/com.parshu.nakamademo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-07-13 18:25:48.251 15856-15889/com.parshu.nakamademo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-07-13 18:25:48.252 15856-15889/com.parshu.nakamademo W/System.err: 	... 1 more
2020-07-13 18:25:48.252 15856-15889/com.parshu.nakamademo W/System.err: Caused by: java.io.IOException: FRAME_SIZE_ERROR: 4740180
2020-07-13 18:25:48.252 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:590)
2020-07-13 18:25:48.252 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:47)
2020-07-13 18:25:48.252 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:137)
2020-07-13 18:25:48.253 15856-15889/com.parshu.nakamademo W/System.err:     at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1075)
2020-07-13 18:25:48.253 15856-15889/com.parshu.nakamademo W/System.err: 	... 3 more

**Note**: Putting code inside quote as the code seems to be not working. Let me know, if I need to put the sample project here.

**Comment by mofirouz** [comment]
You'll need to connect to port `7349` with the Java client.

> By default the client uses connection settings "127.0.0.1" and 7349 to connect to a local Nakama server.

```java
import com.heroiclabs.nakama.Client;

public class NakamaSessionManager {
  private final Client client;

  public NakamaSessionManager() {
    client = new DefaultClient("defaultkey", "127.0.0.1", 7349);
  }
}
```

This isn't an issue. Please follow the documentation thoroughly:

https://heroiclabs.com/docs/android-java-client-guide/#setup
