### ISSUE TITLE
Channel {0} was not shutdown properly!!!

### ISSUE THREAD

**Issue by karan1213** [heroiclabs/nakama-java#48]
Sometimes, I get this exception and the app crashes.

```
2020-11-04 03:00:21.974 7426-7764/com.talke.dev E/io.grpc.l1.e1: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.l1.e1$a.<init>(ManagedChannelOrphanWrapper.java:94)
        at io.grpc.l1.e1.<init>(ManagedChannelOrphanWrapper.java:52)
        at io.grpc.l1.e1.<init>(ManagedChannelOrphanWrapper.java:43)
        at io.grpc.l1.b.a(AbstractManagedChannelImplBuilder.java:518)
        at com.heroiclabs.nakama.DefaultClient.<init>(DefaultClient.java:115)
        at com.heroiclabs.nakama.DefaultClient.<init>(DefaultClient.java:77)
```

**Comment by mofirouz** [comment]
Looks to me that your app is closing but you aren't closing the socket/grpc connection to the server. Do you know if this happens in a lifecycle function in your app?
