### ISSUE TITLE
Android build failure due to protobuf-javalite

### ISSUE THREAD

**Issue by ANURAGX** [heroiclabs/nakama-java#52]
The android build fails because Nakama uses **protobuf-javalite**.
You may wonder why because I need firebase featrues in my app and the firebase uses **protobuf-java** instead of lite version.

And mixining lite and full version of protobuff will result in compilation failures.
I have tried all the possible excludes and it though compiles but results in runtime crash dues to class not found exception.

So the only possible fix is to have **protobuf-java** instead of lite.
Anyone making android game will definately need firebase services.

**Comment by mofirouz** [comment]
There was a similar issue with Firebase before: https://github.com/heroiclabs/nakama-java/issues/31

This was fixed by overriding Nakama's protobuf-lite version to match that of Firebase. Can you please try this locally and make a PR?

**Comment by ANURAGX** [comment]
Actually I have already tried the similar approach.
I forced the same version of protobuf-lite version

`subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                
                if (details.requested.group == 'com.google.protobuf' && details.requested.module.name == 'protobuf.javalite') {
                    details.useVersion "${versionProtobuf}"
                }
            }
        }
    }`

Doing this didn't solve the problem.
Let me try your way also.

**Comment by lugehorsam** [comment]
Hey @ANURAGX, you should try using our fat Jar which namespaces our dependencies and should avoid a conflict with Firebase's version of Protobuf.

The Gradle line would look like this:

`implementation 'com.github.heroiclabs.nakama-java:nakama-java-all:v2.1.1'`

Let me know how that goes.

**Comment by ANURAGX** [comment]
@lugehorsam after doing this the project compiles and builds and launches.
But there is new problem the intellisense is not working around Nakama classes.

Without intellisense its very time wasting to write code for Nakama related features.
Any suggestions???

<img width="978" alt="Screenshot 2021-03-08 at 9 09 26 PM" src="https://user-images.githubusercontent.com/5199691/110343547-9b883280-8052-11eb-9cf5-ffb1ce1ee298.png">

**Comment by lugehorsam** [comment]
@ANURAGX what IDE do you use? It depends how you are configuring Intellisense. If you had configured it via specifying a path to the .jar file, be aware that the name of the .jar is changed when you switch to the shadow jar, since it has an `-all` suffix.

**Comment by ANURAGX** [comment]
@lugehorsam after undoing your changes my intellisense starts working around Nakama classes.

**Comment by ANURAGX** [comment]
@lugehorsam The intellisense not working may be because of this warning.
<img width="1393" alt="Screenshot 2021-03-08 at 10 35 33 PM" src="https://user-images.githubusercontent.com/5199691/110354989-c11b3900-805e-11eb-9c27-291e7e169fa7.png">


`> Task :Launcher:kaptGenerateStubsWithGameDebugKotlin
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: /Users/anurag/.gradle/caches/modules-2/files-2.1/com.github.heroiclabs.nakama-java/nakama-java-all/v2.1.1/292d72e12460c3cbfdc8dbacd64bb9ababcc18c2/nakama-java-all-v2.1.1.jar: Library has Kotlin runtime bundled into it`

**Comment by lugehorsam** [comment]
@ANURAGX interesting, nice find. We should definitely fix that regardless. I'll do some local testing and get back to you.

**Comment by ANURAGX** [comment]
Thanks brother . I will be awaiting for your response.

**Comment by lugehorsam** [comment]
@ANURAGX okay, let's go back to the original problem here.

I added firebase to our android example and ran `./gradlew build` without any build errors:

https://github.com/heroiclabs/nakama-java/commit/4a7ad24fe855dbedc37a515f0c091bba37b8f119

Your duplicate class exception is a build time error, right? Can you confirm that you can successfully run our example on your machine and/or look for differences in your build file?

**Comment by ANURAGX** [comment]
@lugehorsam 
the Nakama's example project builds successfully after adding firebase dependency because of below lines
`configurations {
    implementation.exclude module:'proto-google-common-protos'
    implementation.exclude module:'protolite-well-known-types'
    implementation.exclude module:'protobuf-lite'
    implementation.exclude module:'protobuf-java'
}`

I added these above lines in mine gradle and the build-time errors are gone.

Can you explain why these excludes are?

**Comment by ANURAGX** [comment]
@lugehorsam 
I deployed Nakama on AWS and my android client is crashing. 
As per the crash log I can say the that Nakama server is 3.0+ and client is for 2.0+ versions.
So any ETA on compatible client library for Nakama 3.0.

**Comment by lugehorsam** [comment]
@ANURAGX great find. The key line is `implementation.exclude module:'protobuf-java'`. 

This makes sense since both `protobuf-java` and `protobuf-javalite` share a subset of classes. What's odd is that firebase claims to use `protobuf-javalite` which is consistent with our library, but perhaps that isn't consistent across all of their various packages.

**Comment by lugehorsam** [comment]
@ANURAGX this library is compatible with Nakama 3.0. Can you share your crash log?

**Comment by ANURAGX** [comment]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:606)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: error in frame handler
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:525)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:86)
        at com.drawnzergames.thelastpiecelauncher.api.repo.NakamaRepository$login$1.run(NakamaRepository.kt:16)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: io.grpc.StatusRuntimeException: INTERNAL: error in frame handler
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.IOException: FRAME_SIZE_ERROR: 4740180
        at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:597)
        at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:48)
        at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:138)
        at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by lugehorsam** [comment]
@ANURAGX can you confirm you are connecting to port 7350 instead of 7349?

**Comment by ANURAGX** [comment]
@lugehorsam  sorry I m an idiot, i copied the port from postman and I didn't realise that Nakama android client makes use of gRPC on port 7349.

**Comment by Allan-Nava** [comment]
I got this error about proto

```

/Users/allan/projects/github/nakama-java-master/examples/example-android/app/src/main/java/com/example/nakama_java_test_android/MainActivity.java:62: error: cannot access MessageLiteOrBuilder
                System.out.println( message.getContent());
                                           ^
  class file for com.google.protobuf.MessageLiteOrBuilder not found


```


![Screenshot 2021-04-06 at 14 18 12](https://user-images.githubusercontent.com/22498435/113709631-04f77180-96e3-11eb-913b-d21f04096bdf.png)
