### ISSUE TITLE
Game Crashes when creating socket.

### ISSUE THREAD

**Issue by ANURAGX** [heroiclabs/nakama-java#53]
The Android Game crashes when creating Client Socket.
Steps to reproduce.
1. Do email auth.
2. Once auth is successful, try to create socket and it gives FATAL exception.
3. Below is the MainActivity which I added to example-android and ran the app on android device.

I experienced the same crash in my app, so I tried to repro in the example-android-nakama and it also crashes.

**CRASH-LOGS**
`2021-03-14 12:31:16.869 13269-13304/com.example.androidnakama E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
    Process: com.example.androidnakama, PID: 13269
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/protobuf/GeneratedMessageV3;
        at com.heroiclabs.nakama.DefaultClient.createSocket(DefaultClient.java:180)
        at com.heroiclabs.nakama.DefaultClient.createSocket(DefaultClient.java:170)
        at com.heroiclabs.nakama.DefaultClient.createSocket(DefaultClient.java:165)
        at com.example.nakama_java_test_android.MainActivity$1.onSuccess(MainActivity.java:36)
        at com.example.nakama_java_test_android.MainActivity$1.onSuccess(MainActivity.java:31)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1056)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.protobuf.GeneratedMessageV3" on path: DexPathList[[zip file "/data/app/~~n8xo80R00Y1tjrIpDYoTHw==/com.example.androidnakama-dHygLV7aoY7yVvuPyPG1Lw==/base.apk"],nativeLibraryDirectories=[/data/app/~~n8xo80R00Y1tjrIpDYoTHw==/com.example.androidnakama-dHygLV7aoY7yVvuPyPG1Lw==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.heroiclabs.nakama.DefaultClient.createSocket(DefaultClient.java:180) 
        at com.heroiclabs.nakama.DefaultClient.createSocket(DefaultClient.java:170) 
        at com.heroiclabs.nakama.DefaultClient.createSocket(DefaultClient.java:165) 
        at com.example.nakama_java_test_android.MainActivity$1.onSuccess(MainActivity.java:36) 
        at com.example.nakama_java_test_android.MainActivity$1.onSuccess(MainActivity.java:31) 
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1056) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) `

**CRASH-IMAGE** 
<img width="1632" alt="Screenshot 2021-03-14 at 12 35 22 PM" src="https://user-images.githubusercontent.com/5199691/111060318-dd393300-84c1-11eb-816e-bfa5ca99c211.png">

**MY ADDED MainActivity in example-app.**

`package com.example.nakama_java_test_android;

import android.os.Bundle;
import android.util.Log;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.google.common.util.concurrent.FutureCallback;
import com.google.common.util.concurrent.Futures;
import com.heroiclabs.nakama.DefaultClient;
import com.heroiclabs.nakama.Session;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        String myAWSIP = "";
        final DefaultClient client = new DefaultClient("defaultkey", myAWSIP, 7349, false);
        final ExecutorService executor = Executors.newSingleThreadExecutor();

        try {
            String email = "super@heroes.com";
            String password = "batsignal";
            Futures.addCallback(client.authenticateEmail(email, password), new FutureCallback<Session>() {
                @Override
                public void onSuccess(final Session result) {
                    Log.d("NAMAKA_TAG", "got session: " + result.getAuthToken());
                    System.out.println("got session: " + result.getAuthToken());
                    client.createSocket();
                    executor.shutdown();
                }

                @Override
                public void onFailure(final Throwable throwable) {
                    System.out.println(throwable.getMessage());
                    Log.d("NAMAKA_TAG", throwable.getLocalizedMessage());
                    executor.shutdown();
                }
            }, executor);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            Log.d("NAMAKA_TAG", e.getMessage());
        }
    }
}
`
**CRASH-LOGS-FIREBASE-CRASHALYTICS**
<img width="670" alt="Screenshot 2021-03-14 at 12 39 26 PM" src="https://user-images.githubusercontent.com/5199691/111060365-66e90080-84c2-11eb-8401-80587981c287.png">

**Comment by lugehorsam** [comment]
Thanks @ANURAGX for the great issue report -- we're able to reproduce this and will get back to you shortly.

**Comment by lugehorsam** [comment]
@ANURAGX this should now be fixed in v2.1.2. Please let me know how it goes for you.

**Comment by lugehorsam** [comment]
Also note, there is no longer a need to exclude `protobuf-java` in your own `build.gradle` file in case you were doing that already.

**Comment by ANURAGX** [comment]
Thanks @lugehorsam to fix the issue in very short amount of time , I works now.
