### ISSUE TITLE
I'll close this issue as resolved. Thanks @hyb1234hi

### ISSUE THREAD

**Issue by Allan-Nava** [heroiclabs/nakama-java#57]
I'll close this issue as resolved. Thanks @hyb1234hi

_Originally posted by @novabyte in https://github.com/heroiclabs/nakama-java/issues/29#issuecomment-562843410_

I have the same problem 

2021-04-01 11:50:16.984 22114-22169/com.example.androidnakama E/MainActivity: UNAVAILABLE
2021-04-01 11:50:16.985 22114-22169/com.example.androidnakama W/System.err: io.grpc.StatusRuntimeException: UNAVAILABLE
2021-04-01 11:50:16.985 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.Status.asRuntimeException(Status.java:533)
2021-04-01 11:50:16.986 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
2021-04-01 11:50:16.986 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434)
2021-04-01 11:50:16.986 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
2021-04-01 11:50:16.986 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763)
2021-04-01 11:50:16.987 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742)
2021-04-01 11:50:16.987 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2021-04-01 11:50:16.987 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2021-04-01 11:50:16.987 22114-22169/com.example.androidnakama W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-04-01 11:50:16.988 22114-22169/com.example.androidnakama W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-04-01 11:50:16.988 22114-22169/com.example.androidnakama W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-04-01 11:50:16.989 22114-22169/com.example.androidnakama W/System.err: Caused by: java.net.ConnectException: failed to connect to nakama.ies-italia.it/192.168.1.26 (port 7349) from /:: (port 38642): connect failed: ECONNREFUSED (Connection refused)
2021-04-01 11:50:16.990 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:143)
2021-04-01 11:50:16.990 22114-22169/com.example.androidnakama W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2021-04-01 11:50:16.990 22114-22169/com.example.androidnakama W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2021-04-01 11:50:16.991 22114-22169/com.example.androidnakama W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2021-04-01 11:50:16.993 22114-22169/com.example.androidnakama W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at java.net.Socket.connect(Socket.java:621)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at java.net.Socket.connect(Socket.java:570)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at java.net.Socket.<init>(Socket.java:450)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at java.net.Socket.<init>(Socket.java:250)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:285)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:555)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err: 	... 4 more
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.Linux.connect(Native Method)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:136)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:157)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:135)
2021-04-01 11:50:16.994 22114-22169/com.example.androidnakama W/System.err: 	... 15 more

**Comment by Allan-Nava** [comment]
Fixed it was a problem of haproxy conf
